### ISSUE TITLE
How do I use the trained model

### ISSUE THREAD

**Issue by xiaoniu001** [XingwXiong/Face3D-Pytorch#1]
Is there a python API that can be used for 3D face recognition?

**Comment by XingwXiong** [comment]
Hi, @xiaoniu001 .
You can use pretrained models for fine-tuning or evaluation by correctly specifying the value of `pretrained_model_path` while running the scripts.
However, I'm sorry that I didn't provide a script for prediction. If you wanna use pretrained models for prediction, maybe you could write a script, with slight modification on `evaluation.py`.

**Comment by praveenmanupati** [comment]
Hi, @XingwXiong 
Is there any chance you have script for prediction? Thanks for the help!
