### ISSUE TITLE
1 question about dataset

### ISSUE THREAD

**Issue by zxcv3339** [XingwXiong/Face3D-Pytorch#3]
Good job.
I have 1 question about dataset.
Where is the dataset from? How did you get the depth image?
Thank you for sharing.

Souther

**Comment by XingwXiong** [comment]
I got this dataset from [_2019 BenchCouncil International Artificial Intelligence System Challenges (Trace4)_.](https://www.benchcouncil.org/competition/index.html) As far as I know, this dataset was provided by Intelifusion Inc.

**Comment by zxcv3339** [comment]
Thanks for your reply.
